@username = motoko
@inexistentUsername = motoko2
@existingButNotContact = batou

### Get all contacts

GET {{baseUrl}}/contact?locale=en-US
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Search contacts

@query = spoo

GET {{baseUrl}}/contact?search={{query}}&locale=en-US
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};
