name: thal
services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    network_mode: host
    container_name: stripe-cli
    command: "listen --forward-to localhost:3000/api/payment/webhook/stripe --api-key ${STRIPE_SECRET_KEY}"
