// Generated by Wrangler by running `wrangler types`

interface Env {
  GCP_CLOUD_TTS_API_KEY: string
  GOOGLE_CLIENT_SECRET: string
  GEMINI_API_KEY: string
  STRIPE_SECRET_KEY: string
  STRIPE_ENDPOINT_SECRET: string
  DB: D1Database
  MESSAGE_RATE_LIMIT: RateLimit
}
