// Generated by Wrangler by running `wrangler types`

interface Env {
  DB: D1Database
  MESSAGE_RATE_LIMIT: RateLimit
  LISTEN_RATE_LIMIT: RateLimit
  TRANSLATE_RATE_LIMIT: RateLimit
  GENERATE_CHARACTER_RATE_LIMIT: RateLimit
}
