name = "thal"
compatibility_date = "2025-01-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "thal"
database_id = "01b68bff-27b3-405b-8713-29560c584895"
migrations_dir = "./db/migrations"

[[unsafe.bindings]]
name = "MESSAGE_RATE_LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }
