name = "thal"
compatibility_date = "2025-01-30"

[[d1_databases]]
binding = "DB"
database_name = "thal"
database_id = "c3f5ce62-612e-4aa0-8af0-88f82a535428"
migrations_dir = "./db/migrations"

[[unsafe.bindings]]
name = "MESSAGE_RATE_LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }
