name = "thal"
compatibility_date = "2025-01-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "thal"
database_id = "544366bf-fdc9-4627-aee8-dfd1295aeabd"
migrations_dir = "./db/migrations"

[[unsafe.bindings]]
name = "MESSAGE_RATE_LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "QUERY_USERNAME_RATE_LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 60, period = 60 }

[[unsafe.bindings]]
name = "LISTEN_RATE_LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "TRANSLATE_RATE_LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "GENERATE_CHARACTER_RATE_LIMIT"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 15, period = 60 }

[observability.logs]
enabled = true
