<template>
  <div class="max-w-[800px] mx-auto mb-12 px-4">
    <h1 class="text-4xl text-slate-800 mb-4">
      How Maratongue Works
    </h1>

    <p class="text-slate-900">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus doloribus quo temporibus est? Quia corporis ex omnis magnam doloremque cumque iure voluptas provident unde minus corrupti obcaecati autem, neque esse excepturi fuga consectetur distinctio, ipsam nulla enim reprehenderit officiis molestiae quas? Est cumque cum quo at eaque, quaerat modi esse! Ipsum placeat assumenda dolorum est laborum voluptatum? Quo atque corporis quia nemo dolorum eligendi, totam aperiam. Qui eum facilis ea cupiditate labore natus impedit, quasi molestiae fugiat cumque eaque doloremque repudiandae ullam illo illum. Vero soluta ea deleniti fuga iste necessitatibus adipisci ratione error delectus est magni reiciendis, eveniet eos, similique, harum laboriosam doloribus qui mollitia commodi deserunt autem. Accusantium repudiandae, numquam rem molestias dolor omnis nesciunt dolores debitis delectus, id dolorem consequatur reiciendis nemo molestiae voluptatum maiores laudantium. Ut sit eius esse neque nemo perferendis ratione tempore soluta commodi aperiam quod dolorum ipsa, dolore voluptatum optio laboriosam iusto repellendus non? Expedita harum, sunt ad natus consequuntur odit in, fuga blanditiis, aliquam autem molestiae quia accusamus? Quia, minus nam suscipit fugit maiores ea quidem? A vero aspernatur iusto. Commodi provident vitae nesciunt corrupti reiciendis magnam, doloribus quod modi labore ratione adipisci odit eveniet perferendis? Vel incidunt doloribus minima modi fugit est officiis obcaecati? Omnis perspiciatis praesentium culpa provident iste reiciendis at dolore! Quod, sunt! Laudantium quisquam ea, odit tenetur reprehenderit consequuntur consequatur quod illo reiciendis vitae quia quibusdam, dolor incidunt sint enim impedit magni quas at nisi fugiat? Est eveniet, similique odit sapiente laboriosam alias inventore non porro? Quisquam aut dicta id nisi totam similique cumque ab, dolor placeat quo accusamus temporibus earum soluta labore quis explicabo, quia quos fugiat aliquam, quam impedit. Dolor temporibus a illo quia ipsa, voluptate quod quasi nihil ullam eos, tenetur neque ex! Enim debitis illum suscipit asperiores neque nobis animi minima quisquam quod modi.
    </p>
  </div>
</template>
