@username = motoko

### Find all characters

GET {{baseUrl}}/character?locale=en-US
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Get character

GET {{baseUrl}}/character/{{username}}?locale=en-US
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Delete character

DELETE {{baseUrl}}/character/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};
