@username = motoko

### Find all characters

GET {{baseUrl}}/character
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Get character

GET {{baseUrl}}/character/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Create character

POST {{baseUrl}}/character
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "username": "ishikawa",
  "name": "Ishikawa",
  "description": "A seasoned intelligence expert and a member of Public Security Section 9 in 'Ghost in the Shell.' He is known for his exceptional hacking skills, extensive knowledge of global intelligence networks, and a laid-back yet insightful demeanor that often provides valuable support to his team's operations.",
  "instructions": "Behave like Ishikawa",
  "conversationStarters": ["Hey, Ishikawa!", "Hi, veteran."]
}

### Update character

PATCH {{baseUrl}}/character/ishikawa
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "name": "Ishikawa"
}

### Delete character

DELETE {{baseUrl}}/character/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Create character

POST {{baseUrl}}/character/draft
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "prompt": "Batou from Ghost in the Shell",
  "discoverable": true
}
