### Find all chats

GET {{baseUrl}}/chat
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Search chats

@query = future

GET {{baseUrl}}/chat?search={{query}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Delete chat

DELETE {{baseUrl}}/chat
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Get history

@username = pazu

GET {{baseUrl}}/chat/history/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};
