@username = motoko

### Get all contacts

GET {{baseUrl}}/contact?locale=en-US
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Search contacts

@query = spoo

GET {{baseUrl}}/contact?search={{query}}&locale=en-US
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Get contact

GET {{baseUrl}}/contact/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Add contact

POST {{baseUrl}}/contact
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "username": "motoko",
  "name": "Motoko"
}

### Edit contact

PATCH {{baseUrl}}/contact/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "name": "Motoko Kusanagi"
}

### Remove contact

DELETE {{baseUrl}}/contact/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};
