@username = motoko

### Find all contacts

GET {{baseUrl}}/contact
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Search contacts

@query = beet

GET {{baseUrl}}/contact?search={{query}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Get contact

GET {{baseUrl}}/contact/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

### Create contact

POST {{baseUrl}}/contact
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "username": "motoko",
  "name": "Motoko"
}

### Update contact

PATCH {{baseUrl}}/contact/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "name": "Motoko Kusanagi"
}

### Delete contact

DELETE {{baseUrl}}/contact/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};
