GET {{baseUrl}}/exercise HTTP/1.1

### 

GET {{baseUrl}}/exercise/38

### 

POST {{baseUrl}}/exercise/generate
Content-Type: application/json

{
  "username": "luis",
  "lessonId": 0
}

### 

POST {{baseUrl}}/exercise/verify/38
Content-Type: application/json

{
  "answer": 1
}
