@username = teste

### Send message

POST {{baseUrl}}/message/{{username}}
Content-Type: application/json
Cookie: session={{$dotenv APICLIENT_SESSION_COOKIE}};

{
  "type": "text",
  "value": "Hello, how are you?"
}
