@username = motoko

### Find all personas

GET {{baseUrl}}/persona
Content-Type: application/json
Cookie: auth_session={{$dotenv COOKIE_TOKEN}};

### Get persona

GET {{baseUrl}}/persona/{{username}}
Content-Type: application/json
Cookie: auth_session={{$dotenv COOKIE_TOKEN}};

### Create persona

POST {{baseUrl}}/persona
Content-Type: application/json
Cookie: auth_session={{$dotenv COOKIE_TOKEN}};

{
  "username": "ishikawa",
  "name": "Ishikawa",
  "description": "A seasoned intelligence expert and a member of Public Security Section 9 in 'Ghost in the Shell.' He is known for his exceptional hacking skills, extensive knowledge of global intelligence networks, and a laid-back yet insightful demeanor that often provides valuable support to his team's operations.",
  "instructions": "Behave like Ishikawa",
  "conversationStarters": ["Hey, Ishikawa!", "Hi, veteran."]
}

### Update persona

PATCH {{baseUrl}}/persona/ishikawa
Content-Type: application/json
Cookie: auth_session={{$dotenv COOKIE_TOKEN}};

{
  "name": "Ishikawa"
}

### Delete persona

DELETE {{baseUrl}}/persona/{{username}}
Content-Type: application/json
Cookie: auth_session={{$dotenv COOKIE_TOKEN}};