FROM ubuntu

RUN apt-get update && apt-get install -y openssh-server git

RUN mkdir /var/run/sshd /codeshare

RUN chmod -R 777 /codeshare

RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN echo "Port 2222" >> /etc/ssh/sshd_config

COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["./start.sh"]
