FROM ubuntu

RUN apt-get update && apt-get install -y openssh-server git

RUN mkdir /var/run/sshd /app

RUN chmod -R 777 /app

# Allow the root login via SSH
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN echo "Port 2222" >> /etc/ssh/sshd_config

# Add a startup script to configure the user and password
COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["./start.sh"]
