export interface Category {
  id: number
  name: string
  icon: string
  description: string
  example: string
  color: string
}

export const categories: Category[] = [
  {
    id: 1,
    name: "Travel, Tourism & Transportation",
    icon: "flight_takeoff",
    description: "Practice conversations for traveling abroad, including booking accommodations, asking for directions, and more.",
    example: "A hotel receptionist or a local tour guide.",
    color: "bg-teal-500 hover:bg-teal-500",
  },
  {
    id: 2,
    name: "Shopping & Retail",
    icon: "storefront",
    description: "Characters in a retail setting, such as shopping for clothes, groceries, or electronics, designed to practice consumer interactions.",
    example: "A salesperson or a customer service representative.",
    color: "bg-indigo-500 hover:bg-indigo-500",
  },
  {
    id: 3,
    name: "Food & Beverage",
    icon: "restaurant_menu",
    description: "Characters for practicing conversations in restaurants, cafes, and food-related situations like menu ordering, dietary preferences, and cooking.",
    example: "A chef or a waiter.",
    color: "bg-red-500 hover:bg-red-500",
  },
  {
    id: 4,
    name: "Beauty, Cosmetic & Personal Care",
    icon: "spa",
    description: "Characters for discussing beauty products, skincare routines, and personal care.",
    example: "A makeup artist or a beauty consultant.",
    color: "bg-pink-500 hover:bg-pink-500",
  },
  {
    id: 5,
    name: "Social Situations",
    icon: "people",
    description: "Conversations for parties, events, or meeting new people, helping users build confidence in social settings.",
    example: "A party host or a new friend.",
    color: "bg-purple-500 hover:bg-purple-500",
  },
  {
    id: 6,
    name: "Academic Practice",
    icon: "school",
    description: "Simulate discussions in educational settings, from classroom dialogues to study groups.",
    example: "A professor or a classmate.",
    color: "bg-green-500 hover:bg-green-500",
  },
  {
    id: 7,
    name: "Medical and Emergencies",
    icon: "local_hospital",
    description: "Practice for healthcare visits, describing symptoms, or handling emergencies.",
    example: "A doctor or a first responder.",
    color: "bg-pink-500 hover:bg-pink-500",
  },
  {
    id: 8,
    name: "Science, Technology & Engineering",
    icon: "memory",
    description: "Conversations with tech-savvy or academic characters to learn specific jargon and discuss trends.",
    example: "A tech blogger or a science teacher.",
    color: "bg-cyan-500 hover:bg-cyan-500",
  },
  {
    id: 9,
    name: "Historical Figures",
    icon: "history_edu",
    description: "Interact with characters inspired by famous people or time periods to learn in a fun, historical context.",
    example: "A Victorian-era gentleman or a World War II soldier.",
    color: "bg-amber-500 hover:bg-amber-500",
  },
  {
    id: 10,
    name: "Business",
    icon: "work",
    description: "Focused on professional settings, such as meetings, emails, and workplace interactions.",
    example: "A CEO or a project manager.",
    color: "bg-blue-500 hover:bg-blue-500",
  },
  {
    id: 11,
    name: "Parenting & Family",
    icon: "family_restroom",
    description: "Characters discussing family dynamics, parenting tips, and relationships with children, siblings, or relatives.",
    example: "A parent or a grandparent.",
    color: "bg-orange-500 hover:bg-orange-500",
  },
  {
    id: 12,
    name: "Law & Legal",
    icon: "gavel",
    description: "Characters simulating legal discussions, contracts, rights, and legal procedures.",
    example: "A lawyer or a judge.",
    color: "bg-rose-500 hover:bg-rose-500",
  },
  {
    id: 13,
    name: "Career and Skills",
    icon: "work",
    description: "Characters discussing career advice, job interviews, and professional development.",
    example: "A recruiter or a career coach.",
    color: "bg-blue-500 hover:bg-blue-500",
  },
  {
    id: 14,
    name: "Sports & recreation",
    icon: "sports_soccer",
    description: "Characters discussing sports, fitness, and recreational activities.",
    example: "A coach or a fitness trainer.",
    color: "bg-green-500 hover:bg-green-500",
  },
  {
    id: 15,
    name: "Hotel & Lodging",
    icon: "hotel",
    description: "Characters for practicing conversations in hotels, hostels, and other lodging situations.",
    example: "A hotel receptionist or a concierge.",
    color: "bg-teal-500 hover:bg-teal-500",
  },
  {
    id: 16,
    name: "Humor and Comedy",
    icon: "sentiment_very_satisfied",
    description: "Characters who use humor to teach English.",
    example: "Charlie, the Stand-up Comedian: Introduces jokes, idioms, and witty phrases.",
    color: "bg-yellow-500 hover:bg-yellow-500",
  },
  {
    id: 17,
    name: "Gaming and Entertainment",
    icon: "videogame_asset",
    description: "Characters discussing video games, movies, music, and pop culture.",
    example: "A gamer or a movie critic.",
    color: "bg-amber-500 hover:bg-amber-500",
  },
  {
    id: 18,
    name: "Real Estate",
    icon: "house",
    description: "Characters for practicing conversations in real estate, including buying, selling, or renting properties.",
    example: "A real estate agent or a property manager.",
    color: "bg-blue-500 hover:bg-blue-500",
  },
  {
    id: 19,
    name: "Art & Design",
    icon: "palette",
    description: "Characters related to art, design, and creative fields.",
    example: "An artist or a graphic designer.",
    color: "bg-pink-500 hover:bg-pink-500",
  },
  {
    id: 20,
    name: "Miscellaneous & Others",
    icon: "more_vert",
    description: "Characters that don't fit into other categories.",
    example: "A character with a unique background or profession.",
    color: "bg-gray-500 hover:bg-gray-500",
  },
]
